version: '3'
services:
#  mysql:
#    image: mysql:latest
#    container_name: mysql
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_DATABASE: imhero
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#    volumes:
#      - mysql_data:/var/lib/mysql

  db-master:
    container_name: mysql-master
    build:
      context: ./mysql/master/
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER_PASSWORD: 12345678
      MYSQL_DATABASE: imhero
    ports:
      - "3306:3306"
    volumes:
      - master_vol:/var/lib/mysql
      - ./mysql/master/scripts:/docker-entrypoint-initdb.d
    networks:
      imhero:
        ipv4_address: 172.28.0.2

  db-slave:
    container_name: mysql-slave
    build:
      context: ./mysql//slave
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER_PASSWORD: 12345678
      MYSQL_DATABASE: imhero
    ports:
      - "3307:3306"
    volumes:
      - slave_vol:/var/lib/mysql
      - ./mysql//slave/scripts:/docker-entrypoint-initdb.d
    networks:
      imhero:
        ipv4_address: 172.28.0.3
    depends_on:
      - db-master

  web:
    #    image: imhero-test:latest
    #    platform: linux/amd64
    build:
      context: ./
      dockerfile: dockerfile
    container_name: imhero
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db-slave
    networks:
        - imhero


  mongo:
    image: mongo:5.0.13
    volumes:
      - mongo_data:/data/db
    networks:
      - imhero

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - imhero

  graylog:
    image: graylog/graylog:5.1
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - imhero
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp

volumes:
  master_vol:
  slave_vol:
  mysql_data:
    driver: local
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local

networks:
  imhero:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16