### save

POST http://localhost:8080/api/v1/show/reservation
Content-Type: application/json

{
  "seatId": 7,
  "count": 2,
  "requestTime": "2023-06-24T14:30:00"
}

### cancel
DELETE http://localhost:8080/api/v1/show/reservation
Content-Type: application/json

{
  "seatId": 7,
  "ids": [
    1,
    2
  ]
}

### 예매 조회
GET http://localhost:8080/api/v1/show/reservation
Content-Type: application/json

### 판매형환 조회
GET http://localhost:8080/api/v1/show/reservation/seller
Content-Type: application/json
