logging:
  level:
    root: info
    org.hibernate:
      type:
        descriptor.sql: trace
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%X{uuid}){yellow} %clr(%X{userId}){yellow} %clr(%-40.40logger){cyan} %clr(:){faint} %msg%n"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imhero
#    url: jdbc:mysql://mysql:3306/imhero  # for docker run
    username: imhero
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    slaves:
      slave1:
        name: slave1
        url: jdbc:mysql://localhost:3307/imhero
        username: imhero
        password: 12345678
        driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        default_batch_fetch_size: 100
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  sql.init.mode: always

jasypt:
  encryptor:
#    password: ${jasypt_password}
    password: imhero
---
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:mysql://mysql:3306/imhero
    username: root
    password:
  jpa:
    properties:
      hibernate.format_sql: false
      